### PR TITLE
setBaseDirectory emits an event that contains both the old/new direct…

### PR DESCRIPTION
**Pull request by adamki**
…ory.

### CODE REVIEW

**Comment by adamki** [comment]
@sekharp @rrgayhart and @stevekinney Please see the much improved implementation and let me know if any concerns are still present.

**Comment by adamki** [comment]
@sekharp @rrgayhart and @stevekinney is there an update on this? I would love to see this merged... Or feedback on what to improve.

**Comment by stevekinney** [comment]
Thanks for the ping! 😄

**Comment by adamki** [comment]
Thank you!!!

**Pull request merged**
