### PR TITLE
File stats

### PR DESCRIPTION
**Pull request by jillmd501**
### File Statistics
- Modified `find` method to include f.stats
- Modified return to include the mtime, atime, birthtime
- Modified mock to include stats
- Wrote 3 tests

Shall we start a conversation?
convo-meme

### CODE REVIEW

**Comment by stevekinney** [comment]
file_stats_by_jillmd501_ _pull_request__14_ _stevekinney_file-bin

Oh my.

**Comment by jillmd501** [comment]
LAWDY! What could this mean?

**Comment by JessicaG** [comment]
Well this is fun

**Comment by rrgayhart** [comment]
Some Pull Request Pointers
- When you start to create the PR, always go through the `Files Changed` tab and make sure every file included is relevant `hint: if it takes longer than 30 seconds to open the files changed tab you've committed some cruft`
- Once you make sure every single file in your pull request is relevant, go to your `commits` tab.
- Make sure every commit in that tab is relevant - if they are not, or are misspelled, you will need to rebase and squash those commits.

**Comment by rrgayhart** [comment]
Think of it like someone is making a pizza - and you are offering to add pepperoni to the pizza. If you send them a request to add pepperoni, you should not also have anchovies in there - because they expect pepperoni and they might have fish allergies. And if you have the entire kitchen full of tools, including the pizza cutter, someone is probably going to choke on that pizza.

**Comment by rrgayhart** [comment]
I started that metaphor and had no good way to bail out, btw

**Pull request closed without merging**
