### PR TITLE
BaseDirectory change Even Emitter

### PR DESCRIPTION
**Pull request by adamki**

### CODE REVIEW

**Comment by rrgayhart** [comment]
This PR has some issues:
1. The name of your pull request is not specific enough
2. Did you really change that many files?
3. Where is the description? I definitely can't tell what you changed from looking at the file change (it takes 30 seconds to even load) or the PR description
4. `blah` is not a commit you want in an open source library

**Comment by stevekinney** [comment]
emit_by_adamki_ _pull_request__16_ _stevekinney_file-bin



All of @rrgayhart's comments are pretty much on point. `blah` is not a commit in _my_ open source library. Also, there is no additional documentation of this new feature.

**Comment by stevekinney** [comment]
Just ping me when this is ready, I'd like to release 1.0 this week if possible.

**Comment by adamki** [comment]
Closing this PR. Please see continuation of Event Emiiter implementation [here](https://github.com/stevekinney/file-bin/pull/20).

**Pull request closed without merging**
