### PR TITLE
add setBaseDirectory()

### PR DESCRIPTION
**Pull request by matt-stj**
Base functionality complete - still waiting on https://github.com/stevekinney/file-bin/issues/6 for directory validation.

### CODE REVIEW

**Comment by stevekinney** [comment]
Can you add some documentation to the README?

**Comment by matt-stj** [comment]
Yep, added documentation here (https://github.com/stevekinney/file-bin/pull/13).

**Comment by matt-stj** [comment]
@stevekinney - Went ahead and added the README update to this PR.

**Comment by matt-stj** [comment]
Second round of merge conflict fun.

**Pull request merged**
